### ISSUE TITLE
Mention alternatives

### ISSUE THREAD

**Issue by ao2** [dkogan/python-argparse-generate-manpages-example#1]
Hi,

IMHO it would be helpful to explicitly mention existing alternatives and why they didn't work in your case.

For example:

* in what way the output of help2man is not right (e.g. missing synopsis)? Can help2man be improved to cover your use case?

* What is the problem with a native python solution like https://bugs.python.org/issue14102 ? Is it that it's only for python 3?

Thanks,
   Antonio

**Comment by dkogan** [comment]
Antonio Ospite <notifications@github.com> writes:

> IMHO it would be helpful to explicitly mention existing alternatives and why
> they didn't work in your case.

Sure, I can do that


>   * What is the problem with a native python solution like https://
>     bugs.python.org/issue14102 ? Is it that it's only for python 3?

I don't see what that is proposing. Are you talking about
argparse-manpage? That doesn't work. I'll post why in a bit.

**Comment by dkogan** [comment]
Mentioned.

**Comment by ao2** [comment]
Thank you for the updated blog post.
